# Generated by Django 4.2.30 on 2026-04-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
