# Generated by Django 6.0.4 on 2026-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='matiere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
