# Generated by Django 6.0.4 on 2026-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacherprofile_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
