# Generated by Django 6.0.4 on 2026-05-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_calendarevent_professor_calendarevent_target_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_class', models.CharField(max_length=50, unique=True)),
                ('schedule_data', models.JSONField(default=list)),
            ],
        ),
    ]
