# Generated by Django 6.0.4 on 2026-05-07 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('filiere', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=100)),
                ('annee_etude', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='resources/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validator_badge', models.CharField(blank=True, help_text='e.g. Verified by Prof. X', max_length=50, null=True)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
